### PR TITLE
Reduce dist size by 500 KB - reinstate browserslist, removing transforms for ancient browsers

### PR DESCRIPTION
**Pull request by bradenmacdonald**
## Description

Currently, Paragon is built using Babel's [`preset-env`](https://babeljs.io/docs/babel-preset-env) but _without_ specifying any `targets` nor `.browserslistrc` config file. This [has the unfortunate effect](https://babeljs.io/docs/options#no-targets) that:

> When no targets are specified: Babel will assume you are targeting the oldest browsers possible. For example, @babel/preset-env will transform all ES2015-ES2020 code to be ES5 compatible.
>
> We recognize this isn’t ideal and will be revisiting this in Babel v8.
>
> We recommend setting `targets` to reduce the output code size.

So if you look at any of the files in `dist/`, you'll see that they are being transformed in an extremely inefficient way in order to support pre-ES5 browsers (that are more than a decade old!).

In this PR, I am proposing we change the build to use the recommended `targets: defaults` option. This small change to the config results in a _big_ 500KB savings to the transformed files in `dist` when `npm run build` is run:

Before: 2,919,906 bytes (4.5 MB on disk) for 740 items
After: 2,401,170 bytes (4.1 MB on disk) for 740 items

I have also removed [`@babel/plugin-proposal-class-properties`](https://www.npmjs.com/package/@babel/plugin-proposal-class-properties) and [`@babel/plugin-proposal-object-rest-spread`](https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread) because they're both deprecated (click their links for details), and the replacements are now included in `preset-env` so don't need to be separately installed.

See also https://github.com/openedx/paragon/pull/3283 which makes a similar change for the icons.

## What about compatibility?

This is now using the browserslist `defaults` query which is equivalent to `> 0.5%, last 2 versions, Firefox ESR, not dead`. This is considered [best practice](https://github.com/browserslist/browserslist?tab=readme-ov-file#best-practices). We could change it to [`@edx/browserslist-config`](https://github.com/openedx/browserslist-config) but as far as I can tell that's actually _less_ compatible than the browserslist defaults (because it explicitly specifies only the few browsers supported by Open edX, whereas the browserslist defaults includes old browsers if they have enough marketshare). As an example, they [advise](https://github.com/browserslist/browserslist?tab=readme-ov-file#best-practices) "Don’t remove browsers just because you don’t know them. Opera Mini has 100 million users in Africa and it is more popular in the global market than Microsoft Edge. Chinese QQ Browsers has more market share than Firefox and desktop Safari combined." but Open edX browserslist config has removed those browsers.

## Example

Here is a typical diff showing the simplification that results in the build. This is `dist/Alert/index.js`.

```diff
@@ -1,20 +1,3 @@
-// dist/Alert/index.js
-function _typeof(o) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (o) { return typeof o; } : function (o) { return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o; }, _typeof(o); }
-var _excluded = ["children", "icon", "actions", "dismissible", "onClose", "closeLabel", "stacked"];
-function ownKeys(e, r) { var t = Object.keys(e); if (Object.getOwnPropertySymbols) { var o = Object.getOwnPropertySymbols(e); r && (o = o.filter(function (r) { return Object.getOwnPropertyDescriptor(e, r).enumerable; })), t.push.apply(t, o); } return t; }
-function _objectSpread(e) { for (var r = 1; r < arguments.length; r++) { var t = null != arguments[r] ? arguments[r] : {}; r % 2 ? ownKeys(Object(t), !0).forEach(function (r) { _defineProperty(e, r, t[r]); }) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function (r) { Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r)); }); } return e; }
-function _defineProperty(obj, key, value) { key = _toPropertyKey(key); if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }
-function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == _typeof(i) ? i : i + ""; }
-function _toPrimitive(t, r) { if ("object" != _typeof(t) || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != _typeof(i)) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
-function _extends() { _extends = Object.assign ? Object.assign.bind() : function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
-function _slicedToArray(arr, i) { return _arrayWithHoles(arr) || _iterableToArrayLimit(arr, i) || _unsupportedIterableToArray(arr, i) || _nonIterableRest(); }
-function _nonIterableRest() { throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); }
-function _unsupportedIterableToArray(o, minLen) { if (!o) return; if (typeof o === "string") return _arrayLikeToArray(o, minLen); var n = Object.prototype.toString.call(o).slice(8, -1); if (n === "Object" && o.constructor) n = o.constructor.name; if (n === "Map" || n === "Set") return Array.from(o); if (n === "Arguments" || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)) return _arrayLikeToArray(o, minLen); }
-function _arrayLikeToArray(arr, len) { if (len == null || len > arr.length) len = arr.length; for (var i = 0, arr2 = new Array(len); i < len; i++) arr2[i] = arr[i]; return arr2; }
-function _iterableToArrayLimit(r, l) { var t = null == r ? null : "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (null != t) { var e, n, i, u, a = [], f = !0, o = !1; try { if (i = (t = t.call(r)).next, 0 === l) { if (Object(t) !== t) return; f = !1; } else for (; !(f = (e = i.call(t)).done) && (a.push(e.value), a.length !== l); f = !0); } catch (r) { o = !0, n = r; } finally { try { if (!f && null != t["return"] && (u = t["return"](), Object(u) !== u)) return; } finally { if (o) throw n; } } return a; } }
-function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
-function _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }
-function _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }
 import React, { useCallback, useEffect, useState } from 'react';
 import PropTypes from 'prop-types';
 import classNames from 'classnames';
@@ -26,42 +9,42 @@
 import breakpoints from '../utils/breakpoints';
 import Button from '../Button';
 import ActionRow from '../ActionRow';
-export var ALERT_CLOSE_LABEL_TEXT = 'Dismiss';
-var Alert = /*#__PURE__*/React.forwardRef(function (_ref, ref) {
-  var children = _ref.children,
-    icon = _ref.icon,
-    actions = _ref.actions,
-    dismissible = _ref.dismissible,
-    onClose = _ref.onClose,
-    closeLabel = _ref.closeLabel,
-    stacked = _ref.stacked,
-    props = _objectWithoutProperties(_ref, _excluded);
-  var _useState = useState(stacked),
-    _useState2 = _slicedToArray(_useState, 2),
-    isStacked = _useState2[0],
-    setIsStacked = _useState2[1];
-  var isExtraSmall = useMediaQuery({
+export const ALERT_CLOSE_LABEL_TEXT = 'Dismiss';
+const Alert = /*#__PURE__*/React.forwardRef((_ref, ref) => {
+  let {
+    children,
+    icon,
+    actions,
+    dismissible,
+    onClose,
+    closeLabel,
+    stacked,
+    ...props
+  } = _ref;
+  const [isStacked, setIsStacked] = useState(stacked);
+  const isExtraSmall = useMediaQuery({
     maxWidth: breakpoints.extraSmall.maxWidth
   });
-  var actionButtonSize = 'sm';
-  useEffect(function () {
+  const actionButtonSize = 'sm';
+  useEffect(() => {
     if (isExtraSmall) {
       setIsStacked(true);
     } else {
       setIsStacked(stacked);
     }
   }, [isExtraSmall, stacked]);
-  var cloneActionElement = useCallback(function (Action) {
-    var addtlActionProps = {
+  const cloneActionElement = useCallback(Action => {
+    const addtlActionProps = {
       size: actionButtonSize,
       key: Action.props.children
     };
     return /*#__PURE__*/React.cloneElement(Action, addtlActionProps);
   }, []);
-  return /*#__PURE__*/React.createElement(BaseAlert, _extends({}, props, {
+  return /*#__PURE__*/React.createElement(BaseAlert, {
+    ...props,
     className: classNames('alert-content', props.className),
     ref: ref
-  }), icon && /*#__PURE__*/React.createElement(Icon, {
+  }, icon && /*#__PURE__*/React.createElement(Icon, {
     src: icon,
     className: "alert-icon"
   }), /*#__PURE__*/React.createElement("div", {
@@ -71,7 +54,7 @@
     })
   }, /*#__PURE__*/React.createElement("div", {
     className: "alert-message-content"
-  }, children), (dismissible || (actions === null || actions === void 0 ? void 0 : actions.length) > 0) && /*#__PURE__*/React.createElement(ActionRow, {
+  }, children), (dismissible || actions?.length > 0) && /*#__PURE__*/React.createElement(ActionRow, {
     className: "pgn__alert-actions"
   }, /*#__PURE__*/React.createElement(ActionRow.Spacer, null), dismissible && /*#__PURE__*/React.createElement(Button, {
     size: actionButtonSize,
@@ -87,15 +70,19 @@
 // This is needed to display a default prop for Alert.Heading element
 // Copied from react-bootstrap since BaseAlert.Heading component doesn't have defaultProps,
 // so there seems to be no other way of providing correct default prop for base element
-var DivStyledAsH4 = divWithClassName('h4');
+const DivStyledAsH4 = divWithClassName('h4');
 DivStyledAsH4.displayName = 'DivStyledAsH4';
 function AlertHeading(props) {
-  return /*#__PURE__*/React.createElement(BaseAlert.Heading, props);
+  return /*#__PURE__*/React.createElement(BaseAlert.Heading, {
+    ...props
+  });
 }
 function AlertLink(props) {
-  return /*#__PURE__*/React.createElement(BaseAlert.Link, props);
+  return /*#__PURE__*/React.createElement(BaseAlert.Link, {
+    ...props
+  });
 }
-var commonPropTypes = {
+const commonPropTypes = {
   /** Specifies the base element */
   as: PropTypes.elementType,
   /** Overrides underlying component base CSS class name */
@@ -111,7 +98,8 @@
   as: DivStyledAsH4,
   bsPrefix: 'alert-heading'
 };
-Alert.propTypes = _objectSpread(_objectSpread({}, BaseAlert.propTypes), {}, {
+Alert.propTypes = {
+  ...BaseAlert.propTypes,
   /** Specifies class name to append to the base element */
   className: PropTypes.string,
   /** Overrides underlying component base CSS class name */
@@ -123,7 +111,7 @@
    * more detailed customization is also provided.
    */
   transition: PropTypes.oneOfType([PropTypes.bool, PropTypes.shape({
-    "in": PropTypes.bool,
+    in: PropTypes.bool,
     appear: PropTypes.bool,
     children: PropTypes.node,
     onEnter: PropTypes.func,
@@ -149,17 +137,18 @@
   stacked: PropTypes.bool,
   /** Sets the text for alert close button, defaults to 'Dismiss'. */
   closeLabel: PropTypes.oneOfType([PropTypes.string, PropTypes.element])
-});
-Alert.defaultProps = _objectSpread(_objectSpread({}, BaseAlert.defaultProps), {}, {
+};
+Alert.defaultProps = {
+  ...BaseAlert.defaultProps,
   children: undefined,
   icon: undefined,
   actions: undefined,
   dismissible: false,
-  onClose: function onClose() {},
+  onClose: () => {},
   closeLabel: undefined,
   show: true,
   stacked: false
-});
+};
 Alert.Heading = AlertHeading;
 Alert.Link = AlertLink;
 export default Alert;
```

### Deploy Preview

https://deploy-preview-3284--paragon-openedx.netlify.app

No changes should be discernable.

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [ ] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [ ] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [ ] Were your changes tested in the `example` app?
* [ ] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please request an a11y review for the PR in the [#wg-paragon](https://openedx.slack.com/archives/C02NR285KV4) Open edX Slack channel.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@openedx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bradenmacdonald!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/paragon-working-group`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by brian-smith-tcril** [comment]
After discussing in Paragon working group today we decided it likely makes the most sense to bring back the https://github.com/openedx/browserslist-config/ dependency and update that repo to follow browserslist best practices. That repo is currently set to past 2 major versions to match what was communicated on the edx.org support page, but it absolutely makes sense to increase the coverage to follow best practices. This will ensure we have the same level of support throughout all applications instead of just in Paragon.

**Comment by bradenmacdonald** [comment]
Ah, I wasn't aware that it had been removed at some point: https://github.com/openedx/paragon/issues/2501

That issue says

> browserslist should only be defined in MFEs or any regular applications that render pages on the website, not in component libraries like Paragon.

But this is only true if we distribute Paragon in a "buildless" manner, as .tsx/.jsx source files. As far as I know, none of our MFEs consume Paragon in that way. Since we do have an `npm run build` step and we are using Babel to transform Paragon files from .jsx/.tsx to .js, the config does matter, and right now it is using a bad default.

> After discussing in Paragon working group today we decided it likely makes the most sense to bring back the https://github.com/openedx/browserslist-config/ dependency and update that repo to follow browserslist best practices. That repo is currently set to past 2 major versions to match what was communicated on the edx.org support page, but it absolutely makes sense to increase the coverage to follow best practices. This will ensure we have the same level of support throughout all applications instead of just in Paragon.

Sounds like a good plan! Do you want me to update this PR to add that dependency?

**Comment by bradenmacdonald** [comment]
@brian-smith-tcril OK, I've made that change (restored use of `@edx/browserslist-config`), and this should be ready to go!

In doing so, I had to rebuild all the icon files ("Generated icons do not match committed icons. Please run `npm run build` in the icons directory.") So that made the diff larger. But I kept those changes isolated to one commit, and it means I won't be bugging you later to review https://github.com/openedx/paragon/pull/3283 😛 

Separately, and independent of this PR, I opened a PR to expand `browserslist-config` per upstream recommendations: https://github.com/openedx/browserslist-config/pull/16

**Review by brian-smith-tcril — APPROVED** [review]
Thank you so much for this! The only remaining question I have is should we land this first or land https://github.com/openedx/browserslist-config/pull/16 first.

I think landing this first makes sense, and we can do a small `browserslist-config` version bump PR once https://github.com/openedx/browserslist-config/pull/16 lands.

@adamstankiewicz thoughts?

**Comment by adamstankiewicz** [comment]
@brian-smith-tcril Sounds reasonable to me. I've also approved https://github.com/openedx/browserslist-config/pull/16

Thanks for tackling this, @bradenmacdonald 💯

**Review by adamstankiewicz — APPROVED** [review]

**Comment by brian-smith-tcril** [comment]
@bradenmacdonald looks like this has conflicts and needs a rebase. Once that's done and ci passes again I'm happy to merge it!

**Comment by bradenmacdonald** [comment]
@brian-smith-tcril Rebased!

**Pull request merged**
