### PR TITLE
feat: add outline variant of verified icon, rename previous icon [PAR-700]

### PR DESCRIPTION
**Pull request by xitij2000**
The previous icon called verified_outline is actually an outline variant of the
verified_badge icons, so has been renamed to verified_badge_outline (along with
the relevant renamed components).

A new icon which an outline variant of the verified icon has been added.

Screenshot_20220310_220702

**Concerns**

Changing an existing icon could have unintended side-effects. It would be useful to know where all the existing VerifiedOutline icon is used to those instances can switch to VerifiedBadgeOutline insted.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-6514](https://openedx.atlassian.net/browse/OSPR-6514) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by tecoholic — APPROVED** [review]
@xitij2000 :+1: LGTM

**Review by adamstankiewicz — APPROVED** [review]
LGTM!

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1138&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-03-10+16:20&entry.1917517419=2022-03-11+13:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@adamstankiewicz Is this Blended work by any chance? If so, please add tag in the title.

**Pull request merged**
