### PR TITLE
chore: switch data-testid to kebab case for consistency

### PR DESCRIPTION
**Pull request by cintnguyen**
## Description

- switch data-testid to kebab case for consistency
- moved import to setuptest.js

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by cintnguyen** [comment]
@PKulkoRaccoonGang This should address all your comments from my previous PR, let me know if you need anything else. Thank you!

**Review by PKulkoRaccoonGang — APPROVED** [review]
@cintnguyen I see tests are not working, please take a look at the CI check

**Comment by brian-smith-tcril** [comment]
I'm assuming the CI issues are due to having both RTL and enzyme included in `setupTest.js`.

I'm thinking this isn't an issue on the big enzyme -> RTL PR because enzyme has been fully removed from `setupTest.js` there.

I think the best path forward is to revert the `import '@testing-library/jest-dom';` move from this PR and remove it from `FormAutosuggest.test.jsx`in the bigger enzyme -> RTL PR.

**Review by viktorrusakov — APPROVED** [review]
LGTM! Thanks for making these updates 🙂

**Comment by cintnguyen** [comment]
> LGTM! Thanks for making these updates 🙂

No problem - Thanks Viktor!

**Pull request merged**
