### PR TITLE
[BD-46] fix: prevent stretching in Stack

### PR DESCRIPTION
**Pull request by monteri**
Fix auto stretching for the `Stack` component in the vertical mode

JIRA: [PAR-760](https://openedx.atlassian.net/browse/PAR-760)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @monteri! I've created [BLENDED-1169](https://openedx.atlassian.net/browse/BLENDED-1169) to keep track of it in Jira.   More details are on the [BD-46](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3134685276/BD-46+Paragon+Blended+Support+and+Maintenance) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by monteri** [comment]
I checked [Stack from React Bootstrap](https://react-bootstrap.netlify.app/layout/stack/#stacks) and there is this auto stretching and they allow to manage this on the client side. I changed `display: flex` to `display: inline-flex` that removed auto stretching and if client will set either `display: flex` or `width: 100%` he will receive stretching again.

**Comment by adamstankiewicz** [comment]
> I checked [Stack from React Bootstrap](https://react-bootstrap.netlify.app/layout/stack/#stacks) and there is this auto stretching and they allow to manage this on the client side. I changed display: flex to display: inline-flex that removed auto stretching and if client will set either display: flex or width: 100% he will receive stretching again.

@monteri Ah, I see... I guess it's also explicitly mentioned in the documentation, too, isn't it?

image

OK, good catch. I'm leaning towards keeping the stretching as it is, knowing that it's actually expected behavior. The idea that we'll eventually be able to replace this component with the one from react-bootstrap once we are able to upgrade to Bootstrap 5 in Paragon.

Let's maybe use this PR to explain the default stretching behavior in the component README, similar to react-bootstrap's docs.

**Review by adamstankiewicz — APPROVED** [review]

**Comment by edx-webhook** [comment]
@monteri 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1188&entry.1484655318=https://github.com/monteri&entry.752974735=2022-03-28+12:16&entry.1917517419=2022-03-30+17:21&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
