### PR TITLE
feat: add icons from Learning frontend app

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
## Description

Added new icons from the Learning frontend app which needed in rendering the course outline navigation sidebar.

Feature design: https://www.figma.com/file/gew5tORDX4Q7wxOS8vjqZu/side-nav-OEX?type=design&node-id=548-9267&mode=design&t=CcI9gySq0oJckhbI-0

### Deploy Preview

https://deploy-preview-3031--paragon-openedx.netlify.app/foundations/icons/

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [ ] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [ ] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [ ] Were your changes tested in the `example` app?
* [ ] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@openedx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by brian-smith-tcril** [comment]
I think this is doing the same thing as https://github.com/openedx/paragon/pull/3029, @ihor-romaniuk if 3029 gets merged would that cover your use case?

**Comment by ihor-romaniuk** [comment]
@brian-smith-tcril Yes, it looks like you have added all the necessary icons in your PR. This PR may have been closed, but I left a couple of comments.

**Comment by ihor-romaniuk** [comment]
Waiting for the PR: https://github.com/openedx/paragon/pull/3029

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/3031&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2024-04-10+10:11&entry.1917517419=2024-04-11+18:34&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
