### PR TITLE
fix: make icons package tree-shakeable

### PR DESCRIPTION
**Pull request by viktorrusakov**
## Description

Currently, all of the Paragon icons are included into the bundle if at least one icon is used in the project. This PR adds tree-shaking support to include only used icons into the bundle.

Previously, using `SearchField` component (that uses couple of icons internally) would result in following Paragon bundle, which included all of the icons
image

this PR reduced the bundle to this
Screenshot 2023-07-14 at 11 19 10

### Deploy Preview

Include a direct link to your changes in this PR's deploy preview here (e.g., a specific component page).

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [ ] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [ ] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [ ] Were your changes tested in the `example` app?
* [ ] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @viktorrusakov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by adamstankiewicz — APPROVED** [review]

**Comment by adamstankiewicz** [comment]
This solution definitely helps with the resulting bundle's raw "stat" size; I believe it's still an open question on why the parsed/gzipped size doesn't seem to be changing for a test case that uses the `Container` and a handful of the `Form.*` sub-components, e.g.:

**Without `sideEffects: false`**

image

**With `sideEffects: false`**

image

I'd recommend we still merge/release this `sideEffects: false` change and update any JS libraries that include Paragon in its own bundle (e.g., frontend-component-header). It might still be worth digging into understanding why there's no change for parsed/gzipped sizes, though?

**Comment by viktorrusakov** [comment]
@adamstankiewicz I'm pretty sure parsed and gzipped sizes don't change because webpack itself detects that most of the icons are not used and removes them during the minimization process. I've tested this with our `example` app that uses `frontend-build`'s webpack config and looking at it I see that it [uses](https://github.com/openedx/frontend-build/blob/master/config/webpack.prod.config.js#L174) default minimization plugin which [defaults](https://webpack.js.org/configuration/optimization/#optimizationminimizer) to terser-webpack-plugin, [Terser](https://github.com/terser/terser#compress-options) in turn knows how to remove dead code from the bundle (judging by the fact that it has `dead_code` and `side_effects` options which are both set to `true` by default, meaning Terser will try to remove all unreachable code it can find).

Removing terser plugin (i.e. `...` [line](https://github.com/openedx/frontend-build/blob/master/config/webpack.prod.config.js#L174)) from webpack config results in different bundle sizes depending on `sideEffects` option

Without `sideEffects`
image


With `sideEffects`
image

Sooo I'm 99,9999% sure that currently even though all of the icons are present in the initial bundle of the MFEs that use Paragon, they are removed in the final bundle and don't cause bundle size / performance issues. I also validated it manually with our `example` app by checking resulting bundle manually and I couldn't find redundant icons in it even without `sideEffects: false`. 

I guess this PR only ensures that icons don't get into they initial bundle, even though they would get removed by terser plugin anyway. Still this adds additional guarantee that we don't include all of the icons in the bundle 🙂.

**Comment by openedx-webhooks** [comment]
@viktorrusakov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/2441&entry.1484655318=https://github.com/viktorrusakov&entry.752974735=2023-07-14+08:49&entry.1917517419=2023-07-16+09:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by adamstankiewicz** [comment]
@viktorrusakov Thanks for doing a deeper dive in the bundle assets! Interesting find. So, it seems the output shown by Webpack Bundle Analyzer (i.e., `report.html`) may be a bit misleading by seemingly including all 2300+ icons, even though in reality Terser strips them? I wonder if there's a way to delay the `BundleAnalyzerPlugin` to run _after_ Terser does its thing through minification (assuming it's generating the report before the minification). Food for thought.

**Pull request merged**
