### PR TITLE
feat(i18n) add new languages

### PR DESCRIPTION
**Pull request by igobranco**
Add missing languages that are translated and reviewed from transifex but are missing on the project source code.
Languages:  es-AR, es-ES, it-IT, pt-PT, tr-TR

---- 
Updated:
(removed: cs, fa-IR and fr-CA from this PR)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @igobranco!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@igobranco Looks like there's a commit lint issue, can you have a look.

```
Error: You have commit messages with errors

⧗   input: feat(i18n) add new languages

Add languages: cs, es-AR, es-ES, fa-IR, fr-CA, it-IT, pt-PT, tr-TR
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html
```

**Comment by viktorrusakov** [comment]
Hey @igobranco, thank you for making this contribution! Didn't know Paragon was already translated in so many languages 😮. That's awesome!

Couple of comments about the PR:
1. I think simply adding a `:` (i.e., `feat(i18n): add new languages`) should fix commit lint error. We follow Conventional Commits guideline and it requires to have `:` in commit header to distinguish between type and subject of the commit, you can read more about it [here](https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html)
2. The JSON files you added seem to have wrong format, they should just contain key-value pairs in the format `"<message_id>": "<translated_string>"`, see [ar.json](https://github.com/openedx/paragon/blob/master/src/i18n/messages/ar.json) for the example. I think we have a script that transforms the format in your files to the required one, could you try running `npm run i18n_compile` in the root directory? I think it should fix it.
3. Could you also add new languages to the documentation site config [here](https://github.com/openedx/paragon/blob/master/www/src/config.js#L18) (`code` should match keys you added to the `messages` object in `src/i18n/index.js` )? This would allow us to view new languages and translations on the documentation site.

**Comment by igobranco** [comment]
Hi @viktorrusakov ,
Thank you for spend some time with this PR.

> Didn't know Paragon was already translated in so many languages open_mouth. That's awesome!

Yes, it is great! That is why sent this PR!


> 1. I think simply adding a `:` (i.e., `feat(i18n): add new languages`) should fix commit lint error. We follow Conventional Commits guideline and it requires to have `:` in commit header to distinguish between type and subject of the commit, you can read more about it [here](https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html)

Yes, my bad! I forgot the `:` char.

> 2. The JSON files you added seem to have wrong format, they should just contain key-value pairs in the format `"<message_id>": "<translated_string>"`, see [ar.json](https://github.com/openedx/paragon/blob/master/src/i18n/messages/ar.json) for the example. I think we have a script that transforms the format in your files to the required one, could you try running `npm run i18n_compile` in the root directory? I think it should fix it.

Ok, thanks! I didn't know this. I had to run manually the `tx` command, that is why I didn't run that command.
When I run that I found out that some new languages has translation issues. I only have full access to Portuguese (Portugal) language and not to the other languages. The ones that have issues, I've removed from this pull request.

Languages that I've removed from this PR that have translation issues: cs, fa-IR and fr-CA.

Compilation errors:
```
[@formatjs/cli] [WARN] Error validating message "typ souboru musí být {count, plural, one {{typeString} file} nebo {one of {typeString} files}}." with ID "dropzone.Dropzone.invalidType" in file "./src/i18n/messages/cs.json"
[@formatjs/cli] [WARN] Error validating message "این نوع پرونده باید  {count, plural, one {{typeString} file}  سایر {one of {typeString} files}}." with ID "dropzone.Dropzone.invalidType" in file "./src/i18n/messages/fa_IR.json"
[@formatjs/cli] [WARN] Error validating message "Le type de fichier doit être {count, plural, one {{typeString} file} ou {one of {typeString} files}}." with ID "dropzone.Dropzone.invalidType" in file "./src/i18n/messages/fr_CA.json"
SyntaxError: MISSING_OTHER_CLAUSE
    at parse5 (/home/ibranco/projects/openedx/paragon/node_modules/@formatjs/cli/bin/formatjs:147987:21)
    at compile7 (/home/ibranco/projects/openedx/paragon/node_modules/@formatjs/cli/bin/formatjs:149647:67)
    at async Promise.all (index 2)
    at async compileFolder (/home/ibranco/projects/openedx/paragon/node_modules/@formatjs/cli/bin/formatjs:149707:19)
    at async Command.<anonymous> (/home/ibranco/projects/openedx/paragon/node_modules/@formatjs/cli/bin/formatjs:155032:5)
make: *** [Makefile:53: pull_translations] Error 1

```

> 3. Could you also add new languages to the documentation site config [here](https://github.com/openedx/paragon/blob/master/www/src/config.js#L18) (`code` should match keys you added to the `messages` object in `src/i18n/index.js` )? This would allow us to view new languages and translations on the documentation site.

Done!
Just to inform you that changing the language on the netlify app didn't change nothing on the UI, for me this behavior is kind of strange... but probably the problem is mine that don't know how to view those UI messages in the demo/technical doc site.
https://paragon-openedx.netlify.app/

**Comment by viktorrusakov** [comment]
@igobranco thank you for making the fixes!

> Languages that I've removed from this PR that have translation issues: cs, fa-IR and fr-CA.
>
> Compilation errors:

Yeah, that string usually causes issues because it has complicated syntax... I'll make an action item for myself to figure out a solution to this.

> Done!
> Just to inform you that changing the language on the netlify app didn't change nothing on the UI, for me this behavior is kind of strange... but probably the problem is mine that don't know how to view those UI messages in the demo/technical doc site.

Yeah I think the behaviour of language switcher is definitely not obvious, we already had similar comments, and its in our backlog to improve it. So they way it works right now is that it only affects components and not the whole UI. For example if you go to the [first example in the `Dropzone` component](https://deploy-preview-2230--paragon-openedx.netlify.app/components/dropzone/) and select Turkish language you will be able to see one of the translations you added in this PR 🎉 
image

Note that currently there is no way to tell from the UI in which languages the component has been translated already (e.g., selecting Ukrainian language in the `Dropzone` component will show you default English strings, that's because there are no Ukrainian translations for now). This is also one of the thing we aim to improve 🙂 

These changes look good to me, thanks for making this contribution!

**Review by viktorrusakov — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@igobranco 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/2230&entry.1484655318=https://github.com/igobranco&entry.752974735=2023-04-27+11:11&entry.1917517419=2023-05-02+09:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
