### PR TITLE
[BD-46] fix: fixed odd trapezoid-like underline on active tab in Tabs component

### PR DESCRIPTION
**Pull request by PKulkoRaccoonGang**
## Description

Issues: 
- https://github.com/openedx/paragon/issues/2370
- https://github.com/openedx/paragon/issues/2368

### Deploy Preview

[Tabs component](https://deploy-preview-2377--paragon-openedx.netlify.app/components/tabs/)

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [ ] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [ ] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [ ] Were your changes tested in the `example` app?
* [ ] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PKulkoRaccoonGang!


When this pull request is ready, tag your edX technical lead.

**Review by monteri — APPROVED** [review]

**Comment by viktorrusakov** [comment]
@PKulkoRaccoonGang I think dropdown's bottom border got a little broken when focused
image
it should be the same height as a regular tab's underline.

Also when you select an item in the dropdown and then select a regular tab, the underline of the whole `nav` jumps a little bit (this does not happen on the prod).

**Review by adamstankiewicz — COMMENTED** [review]
Looks like the hover styles for non-active tabs may have been removed?

**Figma**

image

**In deploy preview**

Hovering over active tab has gray background:

image

However, hovering over non-active tab, has no background change:

image

**Review by viktorrusakov — APPROVED** [review]
LGTM. I'll let @adamstankiewicz double-check and merge, it's easy to miss bugs with this one 🙂 

@PKulkoRaccoonGang also, don't forget to add new design tokens to alpha branch after this merges 😁

**Review by adamstankiewicz — APPROVED** [review]
LGTM!

**Comment by openedx-webhooks** [comment]
@PKulkoRaccoonGang 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/2377&entry.1484655318=https://github.com/PKulkoRaccoonGang&entry.752974735=2023-06-15+21:03&entry.1917517419=2023-07-21+12:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
