### PR TITLE
[BD-46] feat: add all MUI icons

### PR DESCRIPTION
**Pull request by viktorrusakov**
## Description

Added exports of all "sharp" MUI icons found in https://www.npmjs.com/package/@material-icons/svg except couple broken ones. Also validated locally with `frontend-app-account` that this change does not increase bundle size in MFEs.

### Deploy Preview

https://deploy-preview-1313--paragon-openedx.netlify.app/foundations/icons

## Merge Checklist

* [x] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [x] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [x] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [x] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [x] Were your changes tested in the `example` app?
* [x] Is there adequate test coverage for your changes?
* [x] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @viktorrusakov! I've created [BLENDED-1239](https://openedx.atlassian.net/browse/BLENDED-1239) to keep track of it in Jira.   More details are on the [BD-46](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3134685276/BD-46+Paragon+Blended+Support+and+Maintenance) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by viktorrusakov** [comment]
@adamstankiewicz We probably need to redesign icons page on the docs site as a result of this PR 🙂

**Comment by viktorrusakov** [comment]
> > @adamstankiewicz We probably need to redesign icons page on the docs site as a result of this PR 🙂
> 
> Great call out, @viktorrusakov! While I don't think a `Icons` page redesign should block this PR, I raised this question to the design team as I agree; it's a bit hard to find the icons you're looking for quickly when it's a big, long list. I suggested possibly:
> 
> * displaying the icons more visually (larger icons, in a grid) instead of one icon per row, though unclear where the `import` statement should go (e.g., maybe clicking on the icon exposes a `Sheet` like in [Material's icon list page](https://fonts.google.com/icons?selected=Material+Icons) or some other reasonable interaction).
> * adding a search field to the page so users can quickly filter icons by name (might be helpful if they don't know the exact name)
> 
> Curious if you had other specific suggestions on redesign for this page?

Yeah, I think search is a must here, nobody wants to scroll through all those icons to find what they need (I think people will just use browser search until we implement a proper one 😅). Couple of ideas I had are:
- display icons in some kind of a grid or a table (Material UI does a great job with that [here](https://mui.com/material-ui/material-icons/))
- remove import text near the icons, I don't think we need it since all icons are exported from the same path, i.e. `'@edx/paragon/icons'`, we can just put some placeholder at the top of the page saying to export specific icon do `import { IconName } from '@edx/paragon/icons';`, and then just display icon names near them or something like this
- also I think copy to clipboard functionality would be great here, e.g. when you click on the `Abc` icon the `import { Abc } from '@edx/paragon/icons';` text is copied to your clipboard (and we display a simple popup to notify users about this)

That's just the initial thoughts I had

And yes, I don't think it's a blocker for this PR and we can file a separate ticket for the UI improvements

**Comment by adamstankiewicz** [comment]
> "except couple broken ones"

@viktorrusakov Which icons were broken? Might be good for us to flag to design in case the broken ones were icons we were hoping to include.

**Comment by viktorrusakov** [comment]
@adamstankiewicz Sorry missed your message 😞. Nevermind about the missing icons, I fixed them in my latest commit, that was stupid by me not to fix it the first time...

The issue was that our build command generated incorrect names for icons that start with numbers, e.g. for `1k.svg` file it would generate `export { default as 1K } from ./1K` but this is incorrect javascript since variable can't start with numbers. I tried looking in Material UI for these icons to see how they name it, but couldn't find them at first, so I decided to just remove them because I thought they were not part of Material Icons. But today I saw that they obviously just name such icons as `OneK`... So I fixed them manually, should be good now 🙁

**Comment by adamstankiewicz** [comment]
@viktorrusakov No worries! Thanks for fixing :)

**Review by adamstankiewicz — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@viktorrusakov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1313&entry.1484655318=https://github.com/viktorrusakov&entry.752974735=2022-05-24+14:13&entry.1917517419=2022-05-27+11:38&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
