### PR TITLE
draft: [PAR-299]  creating a draft pull request

### PR DESCRIPTION
**Pull request by PKulkoRaccoonGang**
Description:
- creating a custom Multiselect component
- added Multiselect component behavior logic
- added styles of the Multiselect component

Youtrack:
https://openedx.atlassian.net/browse/PAR-299

Reviewers:
- [ ] [@viktorrusakov ](https://github.com/ih)

Merge checklist:
- [ ] Demo status: OK
- [ ] All related documentation is updated
- [x] Commits are squashed
- [ ] DevOps notes added

Post merge:
- [x] Delete the working branch (if not needed anymore)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @PKulkoRaccoonGang! I've created [OSPR-6513](https://openedx.atlassian.net/browse/OSPR-6513) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@PKulkoRaccoonGang Thank you for your contribution. Is this Blended work? CC @adamstankiewicz

**Comment by PKulkoRaccoonGang** [comment]
@natabene Thanks. Yes, we work together

**Comment by edx-webhook** [comment]
@PKulkoRaccoonGang Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1135&entry.1484655318=https://github.com/PKulkoRaccoonGang&entry.752974735=2022-03-10+13:21&entry.1917517419=2022-03-17+09:09&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
