### PR TITLE
fix: add fill attribute in SVG

### PR DESCRIPTION
**Pull request by milad-emami**
In some icons, we could not change the color, so in this PR, I added a fill attribute to the SVG file to solve that problem.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @milad-emami!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by adamstankiewicz** [comment]
> In some icons, we could not change the color, so in this PR, I added a fill attribute to the SVG file to solve that problem.

@milad-emami Thanks for the contribution! Curious, though, what version of `@edx/paragon` are you running in your application?

We recently resolved this style issue for all the icons from `material-ui` via this PR (https://github.com/openedx/paragon/pull/1821), where we added the following to the `icons/.svgrrc.js` file:

https://github.com/openedx/paragon/blob/ac5c0ac0302947acb802aba61046a0e47d0746ee/icons/.svgrrc.js#L41-L57

As a result, all the SVGs get processed when running `npm run build` and get the appropriate `fill` attribute, e.g.:

https://github.com/openedx/paragon/blob/ac5c0ac0302947acb802aba61046a0e47d0746ee/icons/jsx/Groups.jsx#L9-L14

When you import icons from `@edx/paragon/icons`, it imports the transformed `*.js` file in the output `./es5` folder, which already has the correct attributes at the latest versions of Paragon (v20.21.3+).

**Comment by mphilbrick211** [comment]
Hi @milad-emami! Thanks for your submission! In addition to the comments/questions above, you will need to fill out a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) in order to get this PR pushed through. Please let me know if you have any questions.

**Comment by mphilbrick211** [comment]
Hi @milad-emami! Tests have been enabled for this PR, but it looks like some of the checks failed.

We also need a completed [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) from you to get this PR through. If you've already submitted one, once the checks are re-run, the CLA check should turn green.

**Comment by mphilbrick211** [comment]
> Hi @milad-emami! Tests have been enabled for this PR, but it looks like some of the checks failed.
> 
> We also need a completed [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) from you to get this PR through. If you've already submitted one, once the checks are re-run, the CLA check should turn green.

Hi @milad-emami! Friendly follow-up on my message above.

**Comment by adamstankiewicz** [comment]
I'm inclined to close this PR as the bug was resolved on a later version of Paragon. The icons modified in this PR are confirmed to be styled correctly as can be seen on this [documentation page](https://paragon-openedx.netlify.app/components/iconbutton/) (e.g., replace the `src={Close}` with `src={Groups}` in the code block).

@milad-emami I'd recommend ensuring you're on the latest version of Paragon. Feel free to re-open if you're still having issues.

**Comment by openedx-webhooks** [comment]
@milad-emami Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/1885&entry.1484655318=https://github.com/milad-emami&entry.752974735=2023-01-03+12:18&entry.1917517419=2023-01-27+20:17&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
