### PR TITLE
ci(deploy): Remove pages deploy step

### PR DESCRIPTION
**Pull request by RageLtd**
## Description

Simply removes the Github Pages deploy step from `release.yml` as mentioned in #2465

This is one of a couple `help-wanted` issues I'm going to grab as part of an application to come work with you folks! :smile: 

~~_Note: I'm waiting on my Contributor Agreement to be sent, but this seems pretty benign_~~
_CLA has been executed as of 1100 MST (GMT-7) Nov 16th_

### Deploy Preview

Include a direct link to your changes in this PR's deploy preview here (e.g., a specific component page).

## Merge Checklist

* [ ] ~~If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.~~
* [ ] ~~Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?~~
* [ ] ~~Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?~~
* [ ] ~~Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?~~
* [ ] ~~Were your changes tested in the `example` app?~~
* [ ] ~~Is there adequate test coverage for your changes?~~
* [ ] ~~Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.~~

(Wow actually _none_ of them apply)

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @RageLtd! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @RageLtd! Thanks for this contribution! Please let me know if you have an questions regarding submitting a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base).

**Comment by RageLtd** [comment]
Hey there, @mphilbrick211! I just signed my side this morning - thanks for reaching out

**Comment by RageLtd** [comment]
To those who care, my CLA has been executed as of 7 minutes ago :sweat_smile: Just not sure how to re-trigger the CLA check

**Comment by viktorrusakov** [comment]
Hi @RageLtd! Changes look good, thanks for taking the time to do this 🙂 However, commitlint check is failing now, and we need to fix that as well before I can merge. Basically, commit message cannot start with the `ci` keyword, replacing it with `build` should fix that. (you can read more about how commit messages should be structured when you make contributions to `openedx` in this [OEP](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html))

Once you do that and push the changes, it should re-trigger the CLA check as well.

**Comment by RageLtd** [comment]
Ah, perfect, thanks for the insight @viktorrusakov! I was reading the `openedx` docs and the Angular commit standards and it looked like the `ci` prefix was what I was looking for (I guess I got lost in the rabbit hole of docs and ended up on the Angular standards!)

Will update!

**Comment by openedx-webhooks** [comment]
@RageLtd 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/2820&entry.1484655318=https://github.com/RageLtd&entry.752974735=2023-11-16+12:03&entry.1917517419=2023-11-17+09:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
