### PR TITLE
[BD-46] fix: fixed duplicate calls in FormRadioSet and FormCheckboxSet

### PR DESCRIPTION
**Pull request by PKulkoRaccoonGang**
## Description

- fixed the problem of duplicate calls during `onChange` for the `Form.RadioSet` and `Form.CheckboxSet` components.

**Issue:** https://github.com/openedx/paragon/issues/2683

### Deploy Preview

[Playground demo](https://deploy-preview-2705--paragon-openedx.netlify.app/playground?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoBuAhgDYCuMANBhTFQGot2AXWwZWPAMpVGVGMgDkAcwBOMGEXloA3MVLlqdAJYUAwgAsYYANYwoXHlXOWbUEVjGTps5ADMWPbV0yCEoaM0YiKGYYcwjFGFEE3HwgvRCKCGiAOmYIRQUAMQhlAFsAJUYoQwgMcMjo2KJ4gEJW%2BS4YLOlleKospjYYQJJSbl4BQeRO7t7%2BwSGdEYBfRbTQ2oiomItrACMIAA9G%2BMTsPEIRtYzs3Pz5ItKnPcON%2Bu24mFbm9oxpxh7eHNBsNRmNHDsXFMuv9ZmAIbY0EEVkFVFRWMoSMhUhgADw4bGg0g4h4lLIAcWUEFYAAd8ZdRsTiqSADKMXYwZg4ADqZkMcIwJkyxQA-DiAPQkrKs9mcgm4yUVKoQCS8OWkIiMEowLAEcBC5QUXVqjAhY7a4B1LZmpbGgbsLDAO0wG300h0wkMhWVaoYJ06kCqKC6nBlWzir1K90e%2BVMrKKn1%2B3UqNREYMUlPh2PxiBRj2M0px701RMgXaDYMAIUGmYL2dzhPzpOzvvm-rAAE8IrqMFUKGzolAcCZO0Qa02i-WiRKs0WVVR62PyZSaZOG5KKVTaXLG1K2Rzubz%2BYLcspRdOC9L99vJU8rPsDnPjRqtW39YaQMbTXV4g7LQ0Ife1q2q2wDGLetguh6q5EjeAEvCWgbBqGUCLre97QTGBZofBrZJqo6hpvho7nqS2EHBhO5kS2gz%2BmW7CVtWJFZGRFGwc497Ufauodl2IA9sY-a2EOI6oXB5HbkxZFzguTEbiu2LilGwxLGg6BLCASxAA)

## Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Netlify deploy preview, if applicable.
* [ ] Does your change adhere to the documented [style conventions](https://github.com/openedx/paragon/blob/master/docs/decisions/0012-css-styling-conventions)?
* [x] Do any prop types have missing descriptions in the Props API tables in the documentation site (check deploy preview)?
* [x] Were your changes tested using all available themes (see theme switcher in the header of the deploy preview, under the "Settings" icon)?
* [x] Were your changes tested in the `example` app?
* [x] Is there adequate test coverage for your changes?
* [ ] Consider whether this change needs to reviewed/QA'ed for accessibility (a11y). If so, please add `wittjeff` and `adamstankiewicz` as reviewers on this PR.

## Post-merge Checklist

* [ ] Verify your changes were released to [NPM](https://www.npmjs.com/package/@edx/paragon) at the expected version.
* [ ] If you'd like, [share](https://github.com/openedx/paragon/discussions/new?category=show-and-tell) your contribution in [#show-and-tell](https://github.com/openedx/paragon/discussions/categories/show-and-tell).
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PKulkoRaccoonGang!


When this pull request is ready, tag your edX technical lead.

**Comment by viktorrusakov** [comment]
@PKulkoRaccoonGang Please add test cases checking that `onClick` handler is only invoked once, so we don't run into this bug in the future.

**Comment by viktorrusakov** [comment]
@PKulkoRaccoonGang Your solution works, but it does not fix the underlying problem -- `getRadioControlProps` getting called in both `FormRadio` (parent component) and `RadioControl` (child component) (same thing in `FormCheckbox`), this will eventually lead to other bugs and also it just seems redundant, only one component needs to use this function.

I think the simplest solution is to remove  `getRadioControlProps` usage from `FormRadio`, it seems useless there and it does not do anything, if you look closely you'll see that we only use `id` and `disabled` props from `radioInputProps`, but they are already present in original `props` and `getRadioControlProps` does not do anything with them, it just copies them and that's all. I think you can simply remove context usage from `FormRadio` because it just does not use it in any way, only `RadioControl` needs to use context and  `getRadioControlProps` function. Rewriting `FormRadio` to this works for me locally, i.e. it does not break any tests and I don't see any behaviour changes on the docs site. Can you validate as well and try it for the `Checkbox` component too?

```jsx
const FormRadio = React.forwardRef(({
  children,
  className,
  controlClassName,
  labelClassName,
  description,
  isInvalid,
  isValid,
  ...props
}, ref) => {
  return (
    <FormGroupContextProvider
      controlId={props.id}
      isInvalid={isInvalid}
      isValid={isValid}
    >
      <div
        className={classNames('pgn__form-radio', className, {
          'pgn__form-control-valid': isValid,
          'pgn__form-control-invalid': isInvalid,
          'pgn__form-control-disabled': props.disabled,
        })}
      >
        <RadioControl ref={ref} className={controlClassName} {...props} />
        <div>
          <FormLabel className={labelClassName}>
            {children}
          </FormLabel>
          {description && (
            <FormControlFeedback hasIcon={false}>
              {description}
            </FormControlFeedback>
          )}
        </div>
      </div>
    </FormGroupContextProvider>
  );
});
```

**Review by monteri — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@PKulkoRaccoonGang 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/paragon&entry.867055334=https://github.com/openedx/paragon/pull/2705&entry.1484655318=https://github.com/PKulkoRaccoonGang&entry.752974735=2023-10-10+08:01&entry.1917517419=2023-10-13+08:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
